settings:
  inventory_file: inv.csv
  steam_api_url: https://steamcommunity.com/market/priceoverview/
  api_delay: 5
  currency: 3
  # 1 = USD (US Dollar)
  # 2 = GBP (British Pound)
  # 3 = EUR (Euro)
  # 4 = CHF (Swiss Franc)
  # 5 = RUB (Russian Ruble)
  # 6 = PLN (Polish Złoty)
  # 7 = BRL (Brazilian Real)
  # 8 = NOK (Norwegian Krone)
  # 9 = SEK (Swedish Krona)
  # 10 = IDR (Indonesian Rupiah)
  # 11 = MYR (Malaysian Ringgit)
  # 12 = PHP (Philippine Peso)
  # 13 = SGD (Singapore Dollar)
  # 14 = THB (Thai Baht)
  # 15 = VND (Vietnamese Dong)
  # 16 = KRW (South Korean Won)
  # 17 = TRY (Turkish Lira)
  # 18 = UAH (Ukrainian Hryvnia)
  # 19 = MXN (Mexican Peso)
  # 20 = CAD (Canadian Dollar)
  # 21 = AUD (Australian Dollar)
  # 22 = NZD (New Zealand Dollar)
  # 23 = CNY (Chinese Yuan)
  # 24 = INR (Indian Rupee)
  # 25 = CLP (Chilean Peso)
  # 26 = PEN (Peruvian Sol)
  # 27 = COP (Colombian Peso)
  # 28 = ZAR (South African Rand)
  # 29 = HKD (Hong Kong Dollar)
  # 30 = TWD (Taiwan Dollar)
  # 31 = SAR (Saudi Riyal)
  # 32 = AED (UAE Dirham)
  # 34 = ARS (Argentine Peso)
  # 35 = ILS (Israeli Shekel)
  # 37 = KZT (Kazakhstani Tenge)
  # 38 = KWD (Kuwaiti Dinar)
  # 39 = QAR (Qatari Riyal)
  # 40 = CRC (Costa Rican Colón)
  # 41 = UYU (Uruguayan Peso)
  

cases:
  - Kilowatt Case
  - Fever Case
  - Fracture Case
  - Recoil Case
  - Dreams & Nightmares Case
  - Snakebite Case
  - Revolution Case
  - Danger Zone Case
  - Spectrum 2 Case
  - Glove Case
  - Clutch Case
  - Gamma 2 Case
  - Falchion Case
  - Prisma 2 Case
  - Gamma Case
  - Prisma Case
  - CS20 Case
  - Shadow Case
  - Spectrum Case
  - Chroma 3 Case
  - Revolver Case
  - Operation Wildfire Case
  - Chroma 2 Case
  - Operation Breakout Weapon Case
  - Horizon Case
  - Chroma Case
  - Operation Broken Fang Case
  - Operation Phoenix Weapon Case
  - Shattered Web Case
  - Operation Vanguard Weapon Case
  - Huntsman Weapon Case
  - Operation Riptide Case
  - CS:GO Weapon Case 3
  - eSports 2014 Summer Case
  - CS:GO Weapon Case 2
  - Winter Offensive Weapon Case
  - Operation Hydra Case
  - eSports 2013 Winter Case
  - Operation Bravo Case
  - CS:GO Weapon Case
  - eSports 2013 Case
